server.port=8080
spring.application.name=api-gateway

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.server.webflux.routes[0].id=health
spring.cloud.gateway.server.webflux.routes[0].uri=lb://customer-company-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/health

spring.cloud.gateway.server.webflux.routes[1].id=auth
spring.cloud.gateway.server.webflux.routes[1].uri=lb://customer-company-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.server.webflux.routes[2].id=companies
spring.cloud.gateway.server.webflux.routes[2].uri=lb://customer-company-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/companies/**

spring.cloud.gateway.server.webflux.routes[3].id=customer-products
spring.cloud.gateway.server.webflux.routes[3].uri=lb://product-warranty-purchase-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/customers/me/products

spring.cloud.gateway.server.webflux.routes[4].id=customer-service-requests
spring.cloud.gateway.server.webflux.routes[4].uri=lb://service-request-service
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/customers/service-requests

spring.cloud.gateway.server.webflux.routes[5].id=customers
spring.cloud.gateway.server.webflux.routes[5].uri=lb://customer-company-service
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/customers/**

spring.cloud.gateway.server.webflux.routes[6].id=purchases
spring.cloud.gateway.server.webflux.routes[6].uri=lb://product-warranty-purchase-service
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/purchases/**

spring.cloud.gateway.server.webflux.routes[7].id=service-requests
spring.cloud.gateway.server.webflux.routes[7].uri=lb://service-request-service
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/api/service-requests/**

spring.cloud.gateway.server.webflux.routes[8].id=company-service-requests
spring.cloud.gateway.server.webflux.routes[8].uri=lb://service-request-service
spring.cloud.gateway.server.webflux.routes[8].predicates[0]=Path=/api/company/service-requests
